version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: reactive_database
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      target: release_image
    environment:
      POSTGRES_HOST: postgres
    depends_on:
      - postgres
    ports:
      - "8080:8080"

networks:
  my-network: